@extends('admin.layouts.app')

@section('title', 'Bookings')
@section('page-title', 'Bookings')

@section('content')
<div class="mb-24 flex items-center justify-between gap-16"><p class="text-body text-muted-gray">Passenger booking requests awaiting operational confirmation.</p><div class="flex gap-8 text-body-sm"><a class="{{ !$status ? 'font-bold text-brand-green' : 'text-muted-gray' }}" href="{{ route('admin.bookings.index') }}">All</a><a class="{{ $status === 'pending' ? 'font-bold text-brand-green' : 'text-muted-gray' }}" href="{{ route('admin.bookings.index', ['status' => 'pending']) }}">Pending</a><a class="{{ $status === 'confirmed' ? 'font-bold text-brand-green' : 'text-muted-gray' }}" href="{{ route('admin.bookings.index', ['status' => 'confirmed']) }}">Confirmed</a></div></div>
<div class="overflow-x-auto rounded-lg bg-canvas-white shadow-md"><table class="w-full min-w-[980px]"><thead class="bg-ghost-fog"><tr><th class="px-16 py-12 text-left text-body-sm">Reference</th><th class="px-16 py-12 text-left text-body-sm">Passenger</th><th class="px-16 py-12 text-left text-body-sm">Trip</th><th class="px-16 py-12 text-left text-body-sm">Travel date</th><th class="px-16 py-12 text-left text-body-sm">Total</th><th class="px-16 py-12 text-left text-body-sm">Status</th></tr></thead><tbody class="divide-y divide-input-border">@forelse($bookings as $booking)<tr><td class="px-16 py-14 text-body-sm font-semibold text-forest-deep">{{ $booking->reference }}<br><span class="font-normal text-muted-gray">{{ $booking->created_at->format('d/m H:i') }}</span></td><td class="px-16 py-14 text-body-sm text-slate-text">{{ $booking->passenger_name }}<br><span class="text-muted-gray">{{ $booking->passenger_phone ?: $booking->passenger_email }}</span></td><td class="px-16 py-14 text-body-sm text-slate-text">{{ $booking->route->name }}<br><span class="text-muted-gray">{{ $booking->schedule->departure_time?->format('H:i') }}@if($booking->returnSchedule) / {{ $booking->returnSchedule->departure_time?->format('H:i') }}@endif</span></td><td class="px-16 py-14 text-body-sm text-slate-text">{{ $booking->travel_date->format('d/m/Y') }}<br><span class="text-muted-gray">{{ $booking->passenger_count }} passenger(s)</span></td><td class="px-16 py-14 text-body-sm font-semibold text-brand-green">{{ number_format($booking->total_amount) }} VND</td><td class="px-16 py-14"><form method="POST" action="{{ route('admin.bookings.update', $booking) }}" class="flex gap-8">@csrf @method('PATCH')<select name="status" class="rounded border-input-border text-body-sm"><option value="pending" @selected($booking->status === 'pending')>Pending</option><option value="confirmed" @selected($booking->status === 'confirmed')>Confirmed</option><option value="cancelled" @selected($booking->status === 'cancelled')>Cancelled</option></select><button class="text-body-sm font-semibold text-brand-green">Save</button></form></td></tr>@empty<tr><td colspan="6" class="px-24 py-32 text-center text-body text-muted-gray">No booking requests found.</td></tr>@endforelse</tbody></table></div>
@if($bookings->hasPages())<div class="mt-24">{{ $bookings->links() }}</div>@endif
@endsection
