@extends('layouts.app')

@php
    $copy = [
        'vi' => ['title' => 'Da gui yeu cau dat ve', 'text' => 'Nha xe se kiem tra thong tin va lien he voi ban de xac nhan.', 'reference' => 'Ma tham chieu', 'status' => 'Trang thai', 'pending' => 'Cho xac nhan', 'trip' => 'Chuyen di', 'return' => 'Chuyen ve', 'total' => 'Tong tam tinh', 'home' => 'Ve trang chu', 'help' => 'Can dieu chinh thong tin?'],
        'en' => ['title' => 'Your booking request was sent', 'text' => 'Our team will review availability and contact you to confirm the booking.', 'reference' => 'Booking reference', 'status' => 'Status', 'pending' => 'Pending confirmation', 'trip' => 'Outbound', 'return' => 'Return', 'total' => 'Estimated total', 'home' => 'Back to home', 'help' => 'Need to change details?'],
        'ru' => ['title' => 'Заявка отправлена', 'text' => 'Наша команда проверит наличие мест и свяжется с вами для подтверждения.', 'reference' => 'Номер заявки', 'status' => 'Статус', 'pending' => 'Ожидает подтверждения', 'trip' => 'Туда', 'return' => 'Обратно', 'total' => 'Предварительная сумма', 'home' => 'На главную', 'help' => 'Нужно изменить данные?'],
    ][$locale];
    $vehicle = fn ($item) => $item->vehicle_type ?: ($item->bus_type ?: 'Sleeper cabin');
@endphp

@section('content')
<section class="booking-success"><div class="success-card"><p class="success-mark">OK</p><h1>{{ $copy['title'] }}</h1><p>{{ $copy['text'] }}</p><div class="success-reference"><span>{{ $copy['reference'] }}</span><strong>{{ $booking->reference }}</strong></div><dl><div><dt>{{ $copy['status'] }}</dt><dd>{{ $copy['pending'] }}</dd></div><div><dt>{{ $copy['trip'] }}</dt><dd>{{ $booking->travel_date->format('d/m/Y') }} · {{ $booking->schedule->departure_time?->format('H:i') }} · {{ $vehicle($booking->schedule) }}</dd></div>@if($booking->returnSchedule)<div><dt>{{ $copy['return'] }}</dt><dd>{{ $booking->return_travel_date->format('d/m/Y') }} · {{ $booking->returnSchedule->departure_time?->format('H:i') }}</dd></div>@endif<div><dt>{{ $copy['total'] }}</dt><dd>{{ number_format($booking->total_amount) }} VND</dd></div></dl><div class="success-actions"><a href="{{ route('home', ['lang' => $locale]) }}">{{ $copy['home'] }}</a><a href="{{ route('contact', ['lang' => $locale]) }}">{{ $copy['help'] }}</a></div></div></section>
@endsection

@push('styles')
<style>.booking-success{min-height:70vh;display:grid;place-items:center;padding:52px 16px;background:#f5faf4}.success-card{width:min(580px,100%);padding:34px;background:#fff;border:1px solid #d9e5dc;border-radius:17px;text-align:center;box-shadow:0 15px 35px rgba(11,127,66,.09)}.success-mark{display:grid;place-items:center;width:46px;height:46px;margin:0 auto 16px;border-radius:50%;background:#0b7f42;color:#fff;font-size:14px;font-weight:900}.success-card h1{margin:0 0 9px;color:#173014;font-size:29px}.success-card>p:not(.success-mark){margin:0;color:#62735e;line-height:1.6}.success-reference{margin:24px 0;padding:16px;background:#fef8e8;border:1px solid #edddb1;border-radius:10px}.success-reference span,.success-reference strong{display:block}.success-reference span{color:#725d14;font-size:12px;font-weight:800;text-transform:uppercase}.success-reference strong{margin-top:4px;color:#173014;font-size:22px;letter-spacing:.06em}.success-card dl{display:grid;gap:14px;margin:0;text-align:left}.success-card dl div{display:flex;justify-content:space-between;gap:16px;padding-bottom:13px;border-bottom:1px solid #e5eee7}.success-card dt{color:#62735e;font-size:13px}.success-card dd{margin:0;color:#173014;font-size:13px;font-weight:800;text-align:right}.success-actions{display:flex;justify-content:center;gap:10px;margin-top:25px}.success-actions a{padding:11px 15px;border:1px solid #0b7f42;border-radius:8px;color:#0b7f42;font-size:13px;font-weight:800;text-decoration:none}.success-actions a:first-child{background:#0b7f42;color:#fff}@media(max-width:480px){.success-card{padding:25px 18px}.success-card dl div{display:grid}.success-card dd{text-align:left}}</style>
@endpush
